CREATE TABLE TaskOption (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    task_id BIGINT (20) NOT NULL,
    option_string VARCHAR(255) NOT NULL,
    isCorrect BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT FK_TaskOption_Task FOREIGN KEY (task_id) REFERENCES Task(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
